### ISSUE TITLE
Testimonial Length

### ISSUE THREAD

**Issue by eetom** [eetom/new-double#7]
I feel that the testimonials are a bit too long, try to find ways to shorten it a bit or it wont be easy to read. The section is meant for more of a short blurb rather than a full article about how they feel. If we want to in the future we can set up maybe a page just for customer stories with more images and in depth.

tl;dr

1) the length of some testimonials are too long (ie. Gene)
2) there are too many testimonials (my personal opinion, no more than 4)
3) for future save these up and put into a page specifically for customer stories etc.

Eric

**Comment by tpun** [comment]
I totally agreed about the length https://github.com/eetom/new-double/issues/3#issuecomment-126988328.
Cary worked on the testimonial and I have also noted this down in the issue #3 
Originally I thought we would just randomly picked a few per page load. Another way to do this given we have a few is to list them instead of doing carousel. Maybe do a grid style with the companies' logos
